### ISSUE TITLE
Python crash in SeeYou export with free format waypoint

### ISSUE THREAD

**Issue by dingetje** [TobiasLohner/proSoar#1]
1. Create a task with a free selected waypoint (a waypoint that is not on the map).
2. Export in SeeYou format
3. resulting cup file contains a Python error instead of a valid SeeYou task.

**Comment by dingetje** [comment]
/home/tobs/prosoar.de/util/bin/public/download_task.py in ()
   64  
   65 
   66 if **name** == '**main**':
   67   main()
   68 
main = <function main>
 /home/tobs/prosoar.de/util/bin/public/download_task.py in main()
   61     print "Content-disposition: attachment; filename=" + taskname + ".cup"
   62     print
   63     print create_seeyou_task(task, taskname)
   64  
   65 
global create_seeyou_task = <function create_seeyou_task>, task = <prosoar.task.task.Task instance>, taskname = '059740'
 /home/tobs/prosoar.de/util/lib/prosoar/task/seeyou_writer.py in create_seeyou_task(task=<prosoar.task.task.Task instance>, taskname='059740')
   18   for key, turnpoint in enumerate(task):
   19     if turnpoint.name == 'Free turnpoint':
   20       turnpoint.name = '{:02d} '.format(key+1) + turnpoint.name
   21  
   22     if key == 0:
turnpoint = <prosoar.task.turnpoint.Turnpoint instance>, turnpoint.name = 'Free turnpoint', '{:02d} '.format = <built-in method format of str object>, key = 1

<type 'exceptions.ValueError'>: zero length field name in format
      args = ('zero length field name in format',)
      message = 'zero length field name in format'

**Comment by dingetje** [comment]
no takers?

**Comment by TobiasLohner** [comment]
fixed
